services:
  postgres-db:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      # Uso de volumen nombrado
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  mongo-db:
    image: mongo:7.0.12
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      # Uso de volumen nombrado
      - mongo-data:/data/db
    ports:
      - 27017:27017


# Definición de volúmenes nombrados
volumes:
  postgres-data:
  mongo-data: